### ISSUE TITLE
Check spacing on FAQ cards when expanded/contracted, e.g. final card does not have space above the footer

### ISSUE THREAD

**Issue by quaid** [operate-first/operate-first.github.io#118]

**Comment by schwesig** [comment]
ok
![image](https://user-images.githubusercontent.com/89909507/179995003-fa884b65-390d-4331-89c1-37a399aa7e53.png)
---
maybe
![image](https://user-images.githubusercontent.com/89909507/179995391-a37a069d-98cd-4683-96a6-4a407f57e226.png)
---
not ok
![image](https://user-images.githubusercontent.com/89909507/179995055-d77b8ab6-8a2d-4d0c-8b11-4430838c4e03.png)
---
not ok
![image](https://user-images.githubusercontent.com/89909507/179995076-20c32eea-d513-4cb7-afad-ddd64738e9f9.png)

**Comment by schwesig** [comment]
belongs together?
https://github.com/operate-first/operate-first.github.io/issues/60
