### ISSUE TITLE
[Blog] When refreshing the block main page, it jumps back to old/basic layout

### ISSUE THREAD

**Issue by schwesig** [operate-first/operate-first.github.io#133]
1. Starting at [operate-first.cloud](https://www.operate-first.cloud/)
1. Clicking link `Blog` in the top right menu
![image](https://user-images.githubusercontent.com/89909507/180711872-cf981938-dab8-492b-ace5-1cdb4441ac73.png)
1. leads to the expected result as planned here https://github.com/operate-first/operate-first.github.io/pull/89)looking
![image](https://user-images.githubusercontent.com/89909507/180712262-c7706e7d-3937-4fc2-b59b-1f28e827c81b.png)
1. refreshing the page leads to the old/ basic layout
![image](https://user-images.githubusercontent.com/89909507/180712459-6b1391db-483b-4ee0-b3bf-ebc8800247d9.png)
---
![Peek 2022-07-25 02-34](https://user-images.githubusercontent.com/89909507/180713035-ebb51d0b-4dcd-4e5e-b20c-8c43e6a099a8.gif)

**Comment by schwesig** [comment]
@traytorous @durandom @quaid
/sig community
/kind website
/kind cleanup
/kind bug

**Comment by durandom** [comment]
resolved. I had to turn off GH pages for the blog repo

**Comment by schwesig** [comment]
@durandom Thanks!
