### ISSUE TITLE
Blog - Top Navigation menu visually jumps compared to the other pages

### ISSUE THREAD

**Issue by schwesig** [operate-first/operate-first.github.io#166]
https://www.operate-first.cloud/
vs
https://www.operate-first.cloud/blog

![Peek 2022-08-02 13-25](https://user-images.githubusercontent.com/89909507/182436614-7c094f20-d70a-4f43-9a39-3158005afc58.gif)

**Comment by Green-Ranger11** [comment]
Could I work on this issue?

**Comment by schwesig** [comment]
Hi @Green-Ranger11,
Yes, please! Awesome. I would appreciate this.
I wasn't able to figure it out.

**Comment by Green-Ranger11** [comment]
The simplest fix is setting a min-height on this blog page as I've done [here](https://github.com/Green-Ranger11/operate-first.github.io/commit/7d92440d0d0d0e8b0ea939dad85b1cf0b0ec1d1f).

Another option would set the min-height on the `layout` component but breaks some pages' styles. Would you be open to a one-line PR?

**Comment by schwesig** [comment]
sure, PRs are fine and good to test also.
Feel free.
thanks for figuring out the two ways.

breaking the style in general is not an option in my opinion.
let's go with the min height.

if I see it right, you are using height.
the jumping is left/ right thing. interesting that this can fix it. didn't think about it.

**Comment by schwesig** [comment]
@Green-Ranger11 awesome works like a charm
great fix
hacktoberfest accepted

**Comment by schwesig** [comment]
@Green-Ranger11 feel free to open issues (e.g. website fixes, design ideas etc) yourself.
