### ISSUE TITLE
Change support link to https://github.com/operate-first/support

### ISSUE THREAD

**Issue by quaid** [operate-first/operate-first.github.io#176]

**Comment by schwesig** [comment]
@quaid I checked the current web pages and all support related links were connected to https://github.com/operate-first/support
do you remember, what page you experienced a not working/ wrong link?

/assign @quaid

**Comment by quaid** [comment]
> @quaid I checked the current web pages and all support related links were connected to https://github.com/operate-first/support do you remember, what page you experienced a not working/ wrong link?
> 
> /assign @quaid

I think this must have been fixed? I don't find any incorrect links, so I'll close this.
