### ISSUE TITLE
update logo and favico on operate-first.cloud/community/open-source-services.html

### ISSUE THREAD

**Issue by schwesig** [operate-first/operate-first.github.io#209]
update logo and favico on https://www.operate-first.cloud/community/open-source-services.html

the old logo ![image](https://user-images.githubusercontent.com/89909507/197259075-b761f6e1-2491-484d-a5e1-13c1ab2aec39.png)
needs to be replaced with this one 
![image](https://user-images.githubusercontent.com/89909507/197259184-9525b62b-fa22-4b29-bfcd-ece55b5e756a.png)

files in  here https://github.com/operate-first/community/tree/0a15ca4c3e9a593c56c7a8c0ad21f02bc50b9881/img
  - [icon.png](https://github.com/operate-first/community/blob/0a15ca4c3e9a593c56c7a8c0ad21f02bc50b9881/img/icon.png)
  - [favicon.png](https://github.com/operate-first/community/blob/0a15ca4c3e9a593c56c7a8c0ad21f02bc50b9881/img/favicon.png)

need to be replaced by files in here https://github.com/operate-first/training/tree/main/courses/course-operate_first_intro
- [ ]   [logo.png](https://github.com/operate-first/training/blob/main/courses/course-operate_first_intro/logo.png) --> icon.png
- [ ]   [favicon-144x144.png](https://github.com/operate-first/training/blob/main/courses/course-operate_first_intro/favicon-144x144.png) --> favicon.png

**Comment by pratik2315** [comment]
Hey @schwesig 
I would like to work on this issue if its alright.

**Comment by Kishore-abhimanyu** [comment]
Can you assign me this issue?

**Comment by schwesig** [comment]
@pratik2315 yes for sure!
feel free :-) looking forward to it

**Comment by pratik2315** [comment]
Hey @schwesig I don't think I understand. Do I have to make changes in 'operate-first/community' repository or this repo itself. I was not able to find any of these icons in this repository. Can you pls clear out my doubts.

**Comment by schwesig** [comment]
Sure, no problem:
the files in this repo are old and need to be updated
https://github.com/operate-first/community/tree/0a15ca4c3e9a593c56c7a8c0ad21f02bc50b9881/img
so, yes, changes need to be made in the repo 'operate-first/community' in the folder 'operate-first/community/img'


sure, no problem. getting the whole setup

**Comment by schwesig** [comment]
https://github.com/operate-first/community
