### ISSUE TITLE
Change/Upgrade the Intro page of the Community Handbook 

### ISSUE THREAD

**Issue by carlosGimeno** [operate-first/operate-first.github.io#48]
Currently, the landing page of the Community Handbook when clicking the ["Community Handbook"](https://www.operate-first.cloud/community-handbook/) in the top Navbar is not very detailed and still references the Hitchiker Guide, which was replaced with the Community Handbook on a previous PR. I suggest replacing this page with the [General/Intro page](https://www.operate-first.cloud/community-handbook/main/README.md), which includes the data in the original page as well as other key details.

**Comment by Gregory-Pereira** [comment]
@carlosGimeno I am going to close this seeing as it was identified as a duplicate of https://github.com/operate-first/community-handbook/issues/26. Feel free to reopen if this is not the case.
