### ISSUE TITLE
Where do we add all services groups tutorial to operate first website?

### ISSUE THREAD

**Issue by pacospace** [operate-first/operate-first.github.io#49]
https://github.com/AICoE/overlays-for-ai-pipeline-tutorial/issues/4
https://github.com/AICoE/manage-dependencies-tutorial/issues/4
https://github.com/AICoE/elyra-aidevsecops-tutorial/issues/389

**Comment by Gregory-Pereira** [comment]
@pacospace, can we close this issue?
/remove-lifecycle stale
