### ISSUE TITLE
Document / Site Search

### ISSUE THREAD

**Issue by durandom** [operate-first/operate-first.github.io#51]
We could also implement some sort of document search to index the docs and tags if that interests

as per https://github.com/operate-first/operate-first.github.io/pull/14#issuecomment-693525036

**Comment by Gregory-Pereira** [comment]
I see that this issue is still not assigned to anyone, and not currently active. Is this still a priority for us @durandom? If not can we close it? Alternatively maybe if we dont want to implement a search some Google dork commands could be provided in documentation?

/remove-lifecycle stale

**Comment by durandom** [comment]
can be closed. the site doesnt have too much content anyway
