### ISSUE TITLE
Create dynamic margin/padding for nav-pages

### ISSUE THREAD

**Issue by bryanmontalvan** [operate-first/operate-first.github.io#60]
## Description
Currently we have fixed padding between our bottom components and footer component on our nav-item pages. Depending on what type of content we have the pages can at times become too long (which looks worse on mobile)

**Preview of this:**
![image](https://user-images.githubusercontent.com/68972382/169895784-62b58715-941c-4468-8f52-7cdc6da0514c.png)
(Look at this on mobile :nauseated_face: )
![image](https://user-images.githubusercontent.com/68972382/169896017-9862bb4c-5d6e-44cf-809b-203a23736946.png)

## Getting started
Go to `/src/components/nav-tabs` where each nav-tab page lives. There you'll find a component with a some sort of styling 
`<Container pb={350}>` or `<Center className={classes.hero}>` where
```css
hero: {
 paddingBottom: 500
 .
 .
} 
```
Make it so that the padding is more dynamic instead of being fixed to a specific pixel value. Or if you want you can replace it with margins instead!

**Comment by svihang8** [comment]
@bryanmontalvan 
@sesheta 
Hello! I would like to work on this issue.

**Comment by bryanmontalvan** [comment]
Hello @svihang8 sounds good! Feel free to work on it.

Look at our [README](https://github.com/operate-first/operate-first.github.io/blob/main/README.md) on how to install the website's codebase. And then submit a PR and we'll review it :)
