### ISSUE TITLE
Link to Community and Community Handbook

### ISSUE THREAD

**Issue by durandom** [operate-first/operate-first.github.io#76]
I can't find easy links to those two assets:
* https://www.operate-first.cloud/community/README.html
* https://github.com/operate-first/community-handbook

@quaid and what do you think about merging the above two repos?

@schwesig maybe link the "Operate First community planning repository" from https://www.operate-first.cloud/our-community/ ?
And with one of those bold call to action buttons?

**Comment by schwesig** [comment]
working on

> * [operate-first.cloud/community/README.html](https://www.operate-first.cloud/community/README.html)
--> https://www.operate-first.cloud/data-scientist/  under black box ```Open community cloud```
--> https://www.operate-first.cloud/our-community under yellow box ```Operate First community resources```


> * [operate-first/community-handbook](https://github.com/operate-first/community-handbook)

**Comment by schwesig** [comment]
fixes in https://github.com/operate-first/operate-first.github.io/pull/195
